# @package _global_

defaults:
  - _self_
  - launcher: slurm_gpu
  - job
  - dataset: mnist
  - override hydra/launcher: submitit_slurm

name: ${dataset_name}
run: 0
seed: null
nosave: False
logger: Wandb

# checkpoint
checkpoint_dir: null
checkpoint_path: null

# training
loss_name: vr_iwae_loss_v2  # vr_iwae_dreg_loss_v6
alpha: 0
optimizer: Adam
lr: 1e-3
max_epochs: 1000
check_val_every_n_epoch: 100
checkpoint_every_n_epochs: 100
batch_size: 100
test_batch_size: 10
N: 100
test_N: 5000

# model
latent_dim: 50
model:
  network_type: MLP
  net_dims: [200, 200]
  distribution_type: Bernoulli
  nonlinearity: tanh

paths:
  experiments_dir_name: experiments
  data_dir_name: data